name: Our CI

on:
  pull_request:
  push:
    - main
    - other-branch
  workflow_dispatch:
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
