name: Publish slides

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
      
      # Generate slides
      - name: Install markdown-slides package
        run: python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git
      - name: Generate slides
        run: mdslides slides.md --output_dir slides

      # Upload page
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: ./slides

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
  